reactioncommerce/catalyst

.snyk, README.md, docs/architecture/decisions/0007-publish-components.md, docs/developing.md, package.json, package/README.md, package/scripts/postbuild.js, package/src/components/Button/Button.js, package/src/components/Button/Button.test.js, package/src/components/Button/__snapshots__/Button.test.js.snap, styleguide.config.js, styleguide/src/sections/Introduction.md, styleguide/src/sections/LocalDevelopment.md, yarn.lock
Type: **docs**
- Update docs in various places
- Update dev dependencies to resolve lint and test issues
- Update tests
- Add resolution for `lodash` security vuln
- Updated the snyk ignore for the unfixable dev dependency vuln for the `mem` package
1. Read through the docs and ensure that references to the `component-library` are replaced with `catalyst`.
1. All tests should be passing on CI, and there should be a preview site published for this PR.
=> docs: update catalyst references

styleguide/src/sections/LocalDevelopment.md
Use correct paths for volumes when developing locally inside fo Reaction admin.
=> refactor: use correct paths for volumes when developing locally

package/package.json
Type: **chore**
This fixes issues with using docker volumes to link the `dist` folder into a project like Reaction.
none
1. Follow the steps here to link the `package/dist` directory into the `Reaction Admin`: https://catalyst.reactioncommerce.com/#/Introduction/Developing%20Locally%20Inside%20Another%20Project
2. Change things in catalyst components and run `yarn build` multiple times from the package directory.
3. Your Reaction Admin should reload with the new changes
=> chore: use glob pattern to remove files in prebuild

styleguide.config.js, styleguide/src/components/ComponentsListRenderer.js
Resolves #15 
- Make the menu sections collapsible.
- The top-level sections are collapsed by default.
- All sub-sections are expanded by default. These include "Actions" and "Feedback" under "Base Components"
none
1. Open the docs site and you should see all top-level menus in their collapsed state
2. Click on any menu item to expand. (if it has a page will be navigated to, we should probably remove these section pages in another PR)
3. Click on any component docs or sub-item to navigate to that doc
4. Refresh.
5. The selected item should remain selected, and the menu expanded for that sub-item
=> feat: collapsible menus

.reaction/scripts/templates/Component.js.template, .reaction/scripts/templates/Component.test.js.template, babel.config.js, config/paths.js, package.json, package/src/components/Button/Button.js, package/src/components/Button/Button.md, package/src/components/Button/Button.test.js, package/src/components/Button/__snapshots__/Button.test.js.snap, package/src/components/ConfirmDialog/ConfirmDialog.test.js, package/src/components/ConfirmDialog/__snapshots__/ConfirmDialog.test.js.snap, package/src/components/DialogTitle/DialogTitle.test.js, package/src/components/DialogTitle/__snapshots__/DialogTitle.test.js.snap, package/src/setupTests.js, package/src/tests/index.js, yarn.lock
Resolves #29 - themes
Resolves #16 - docs
Resolves #19 - tests
Impact: **major**  
Type: **bugfix|style|docs|tests**
- add mui theme to Button
- renames danger button to Error button
- remove Enzyme, React Test Renderer
- add https://testing-library.com/docs/react-testing-library, and Jest-dom
- create `renderWithProviders` to add mui theme provider to test renderer
- adds `react-testing-library`
- adds `jest-dom`
- removes `enzyme`
- removes `react-test-renderer`
- Updates test template to use react-testing-lib and jest-dom.
- Danger button is now Error button. Change all `color="danger"` to `color="error"`
1. Button docs: https://deploy-preview-32--heuristic-perlman-0ef024.netlify.com/#/Base%20Components/Actions/Button
1. Test …
=> fix(button): add muitheme to button; add Error button; add reactestlib; fix all tests

package/src/components/Chip/Chip.js, package/src/components/Chip/Chip.md, package/src/components/Chip/Chip.test.js, package/src/components/Chip/__snapshots__/Chip.test.js.snap, package/src/components/Chip/index.js, styleguide.config.js, styleguide/src/sections/Content.md
Resolves #25
Chip
See docs for 'Chip'; Confirm that it is behaving as expected. Note that the variant 'outlined' is used as default, unlike regular MUI; This behavior was brought over directly from Reaction.
=> feat: add Chip component

package/src/components/Button/Button.js
Resolves #
Impact: *minor**  
Type: **docs|chore**
- docs: change `danger` to `error` to reflect the code correctly
- code: delete comments
None
1. Read the docs
=> docs(button): change danger to error; remove comments

package/src/components/Button/Button.md, package/src/theme/defaultTheme.js
Resolves #55 
Impact: *minor*  
Type: **feature|bugfix|style**
- Add fontWeight, fontSize for all buttons
- Add smaller fontSize for text buttons
- Add border color and text color for outlined buttons
None
1. Look at Button docs and compare with Zeplin: https://app.zeplin.io/project/5bda33eeed47f75de8f57ffb/styleguide/components?coid=5d48d04bf95862313a34431e
=> fix(button): add correct fontsize, fontweight and document

.snyk, package/src/theme/defaultTheme.js
Impact: **major**  
Buttons, and other actions possibly
none.
1. Hover over the text button.
2. See the BG is not black, but a softer grey
=> fix: revert hoverOpacity to default theme value

package/src/components/Chip/Chip.js, package/src/components/Chip/Chip.md, package/src/components/Chip/Chip.test.js, package/src/components/Chip/__snapshots__/Chip.test.js.snap, package/src/theme/defaultTheme.js
Resolves #52 
Type: **feature|style|docs**
- Add styles to create a Deletable chip: Use `default` variant with `onDelete()`
- Add styles to create a Deletable chip in small/secondary size and color, for MultiSelect: Use `default` variant with `small` size, `secondary` color and `onDelete()`
- Add test cases for the 2 new types of Chips; update snapshots
- Fix a previous error type Chip test
How it will be used in Admin:
How it looks:
None
1. Test regular state
1. Test hover state
1. Test regular state
1. Test hover state
1. Test size is set to small
=> feat(Chip): add deletable Chip, deletable Chip in small/secondary types

package/src/theme/defaultTheme.js
Resolves #67 
Type: **bugfix|style**
- Change the `defaultTheme`'s `MuiButton`'s `root` style to use `1.5`, not `1.75` as line-height. This results in the overall button being 40px high for regular, and 29px/30px high for `small` height buttons. Currently, the buttons are coming out to 44px high.
- Docs: Show an example of a ButtonGroup with a Text Only next to a Contained button
None
1. Test Button in short and default, in contained and outlined
1. Test SplitButton
1. Test the ConfirmDialog, which has a Button in it
=> fix(button): set line-height to 1.5, resulting in 40px high buttons

package/src/components/Select/__snapshots__/Select.test.js.snap, package/src/components/SplitButton/SplitButton.js, package/src/theme/defaultTheme.js, styleguide/src/sections/Typography.md
Resolves #50 
- Add letterspacing to defaultMuiTheme
- Document every type type and document how to use it
- Set the defaultTheme's ListItemText to always use `body1`, which would be reflected in the SplitButton
None
1. @cassytaylor - Test that the docs pg examples look good
1. @mikemurray - Test that the SplitButton looks good
=> docs(typography): add letterspacing variables and add it to all the default typography types

package/src/components/Button/Button.md, package/src/theme/defaultTheme.js
Resolves #74 
- All chips are height 32, unless they are `small`, which is 28.
- Deletable Chip (non-Select type): Background color is `colors.black05`, border is `colors.coolGrey`
- None
1. Deletable chip height
1. Deletable chip colors
=> fix(chip): chip height is 32; deletable chip colors are different.

package/src/components/ActionMenu/ActionMenu.js, package/src/components/ActionMenu/ActionMenu.md, package/src/components/ActionMenu/ActionMenu.test.js, package/src/components/ActionMenu/__snapshots__/ActionMenu.test.js.snap, package/src/components/ActionMenu/index.js, styleguide.config.js
Resolves #73
ActionMenu component based on the Catalyst button and MUI Menu components.
none
1. Open the ActionMenu docs and play around with it
=> feat: add ActionMenu component

package/src/components/Select/Select.js, package/src/components/Select/Select.md, package/src/components/Select/__snapshots__/Select.test.js.snap, package/src/components/Select/helpers/IndicatorSeparator.js, package/src/components/Select/helpers/Menu.js, package/src/components/Select/helpers/NoOptionsMessage.js, package/src/components/Select/helpers/Option.js, package/src/components/Select/helpers/index.js, package/src/theme/defaultTheme.js
Resolves #71 
- Placeholder text should be 14px, not 16px for both the single and multi Select
- A lot of style/design changes.
This component requires the latest version of `react-select`. Using this component in an app with older versions of `react-select` will have to be updated.
1. Design review
1. Code review
=> fix(select): update style for select

package/src/components/ActionMenu/ActionMenu.js, package/src/components/ActionMenu/ActionMenu.md, package/src/components/ActionMenu/ActionMenu.test.js, package/src/components/ActionMenu/__snapshots__/ActionMenu.test.js.snap
Resolves #84
`ActionMenu` meets `ConfirmDialog`. It's now possible to declare options as `confirmable` by supplying `confirmTitle` and/or `confirmMessage`, which will show a `ConfirmDialog` when the item is selected.
Also, allow defining an `onClick` method for each option.
none
1. Check the docs here: https://deploy-preview-85--heuristic-perlman-0ef024.netlify.com/#/Components/Actions/ActionMenu
2. Play around with the "Options with confirmation" example
3. "Filter by file" is not guarded, while the rest the options are
=> feat: confirmable options in ActionMenu

package/src/components/Select/Select.js, package/src/components/Select/helpers/IndicatorSeparator.js
Resolves none
Impact: **major**  
- IndicatorSeparator: use `useTheme`
- Select: remove hardcoded color and use `theme` variable
Confirms the colors of the arrow, V, or the separator, |,  have not changed:
None
1. Test that this works in Reaction Admin
1. Test that the visual style has not changed
=> fix(select): use useTheme for IndicatorSeparator

package/src/components/Select/__snapshots__/Select.test.js.snap, package/src/components/Select/helpers/IndicatorSeparator.js
Resolves none
Inner props are unnecessary for this component.
None
1. Check to ensure it works in Reaction Admin w/o any console logs/errors/warnings
=> fix(select): remove props from indicatorselector

styleguide.config.js, styleguide/src/sections/Introduction.md, styleguide/src/sections/Status.md, styleguide/src/styles.css
Resolves #64 
Type: **docs**
- Rename `Introduction` to `Overview`
- Add `Component status` page with the latest Reaction and Catalyst release data
- Style remove that [ ] square icon thing
- Title case all titles
1. Check the sidenav
1. Check the status page
=> docs(status): update Navigation structure; add Component status page

package/src/theme/defaultTheme.js
Resolves #95 
- Type should be semibold
None
1. Test individually
1. Test in the ConfirmDialog
=> fix(dialogtitle): title should be semibold

package/src/theme/defaultTheme.js
#90 
This white/grey border bug still exists on Reaction Admin:
Tablet mode
Desktop
Confirmed by running Reaction Admin locally w/ this branch:
=> fix(sidebar): fix border overrides

package/src/theme/defaultTheme.js, styleguide/src/sections/Card.md
Resolves #91 
Resolves #90
- Top padding b/w Title and border should be 32px
- Secondary text color should be coolGrey500
Note: For Quick Edit cards (Card that have an X), the top padding will still be a little off, b/c of the padding change that the X adds. This will be addressed in a future ticket.
Confirmed on Reaction Admin locally:
Secondary text color and top padding is now correct.
none
1. Look at examples in branch deploy
1. Use in Reaction Admin's Product Table tag to confirm fix
=> fix(card): correct padding top and secondary text color

package/src/components/SplitButton/SplitButton.js
Resolves #89 
SplitButton should not have padding above/below the MenuItems.
Alternate option: MenuList's padding could be disabled by default in the theme with props, b/c I've confirmed with @cassytaylor that the SplitButton, ActionMenu and other MenuLists used in the app  should not have this padding. 
none
1. Check SplitButton padding
=> fix(splitbutton): disable menulist padding

package/src/components/Button/Button.md, package/src/theme/defaultTheme.js, styleguide/src/styles.css
Resolves #98 
Type: **bugfix|docs**
- Add 1.5px to total height so that height is at 40px
none
1. Test a Text only button next to a Contained or Outlined one, and compare their heights
=> fix(button): text-only button should be 40px

.circleci/config.yml
Resolves #105 
Impact: **major**  
Type: **chore**
- Remove Snyk as a CI build step
=> chore: remove snyk-security step from workflow

styleguide.config.js, styleguide/src/sections/QuickEditCard.md
Resolves #107 
Type: **bugfix|docs**
- Add example of Quick Edit card with animation when it opens and closes
Look at the branch deploy
No
1. Open a card
2. Close a card
=> docs(card): add Card with Grow example

package/src/components/Chip/Chip.js, package/src/components/Chip/Chip.md, package/src/components/Chip/__snapshots__/Chip.test.js.snap
Impact: minor
Type: feature
Adds support for setting the following prop values: `new, processing, canceled` for the `color` property.
1. Start the project and verify the prop values mentioned above can indeed by set on a `Chip` component.
=> feat: add color variants to Chip component

package/src/components/DataTable/DataTable.js, package/src/components/DataTable/DataTable.md, package/src/components/DataTable/__snapshots__/DataTable.test.js.snap, package/src/components/DataTable/helpers/useDataTable.js, package/src/components/DataTable/helpers/useDataTableCellProps.js
Resolves #117 
Adds a row click callback, as well as cell/header props to the `DataTable` Component and `useDataTable` hook;
1. Click the rows in the DataTable example and look and loot at the console.log messages
**First table and last table examples are with clickable rows.**
=> feat: DataTable row click

styleguide/src/sections/Status.md
At the end of every cycle, I update the status page with the latest components:
=> docs(status): add DataTable, Toast

package.json, package/package.json, package/src/components/DataTable/DataTable.js, yarn.lock
Resolves #122 
- Remove unused prop on the page select text field in DataTable
- Update peer dep of the `prop-types` package to 15.7.2
- Update the dependency of docs site for prop-types to match 
none
1. Go to the DataTable docs, see that there is no warnings for `ForwardRef(SomeComponent)`, or `disableUnderline`
=> fix console warnings/errors
